package ufs.game;

public enum MothershipAction {
    NONE,
    ADD_WHITE_SHIP_1,
    ADD_WHITE_SHIP_2,
    REVERSE_EXCAVATOR_1,
    REVERSE_EXCAVATOR_2,
    REVERSE_EXCAVATOR_3,
    REDUCE_RESEARCH_1,
    REDUCE_RESEARCH_2,
    GAMEOVER
}
